<?xml version="1.0"?>
<package format="3">
  <name>map_server</name>
  <version>0.1.0</version>
  <description>This package contains a map_server node which reads in Occupancy Grid from yaml confioguration and publishes it.</description>
  <maintainer email="soenke.prophet@gmail.com">Sönke Prophet</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>yaml-cpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>