name: Colcon Build Test (Release Mode)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Colcon Build (Release)
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - ros_distro: rolling
            runs_on: ubuntu-26.04
          - ros_distro: humble
            runs_on: ubuntu-22.04
          - ros_distro: iron
            runs_on: ubuntu-22.04
          - ros_distro: jazzy
            runs_on: ubuntu-24.04
          - ros_distro: kilted
            runs_on: ubuntu-24.04
          - ros_distro: lyrical
            runs_on: ubuntu-26.04
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Build with Colcon (Release Mode)
        run: |
          mkdir -p ~/ros2_ws/src
          ln -s $GITHUB_WORKSPACE ~/ros2_ws/src/map_server
          cd ~/ros2_ws
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug --packages-select map_server
